"""add_super_admin_enum_and_seed_roles

Revision ID: 262441f6e09b
Revises: 63485bc65e78
Create Date: 2025-04-07 18:23:45.123456
"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import table, column, String, Integer

from app.enums.roles_enums import RoleEnum

# revision identifiers, used by Alembic.
revision: str = '262441f6e09b'
down_revision: Union[str, None] = '63485bc65e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE role_enum ADD VALUE IF NOT EXISTS 'super_admin'")
    
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
