"""add_the_roles_to_the_role_table

Revision ID: d4f357f05e37
Revises: 262441f6e09b
Create Date: 2025-04-07 16:29:10.227783

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import table,column,String,Integer


# revision identifiers, used by Alembic.
revision: str = 'd4f357f05e37'
down_revision: Union[str, None] = '262441f6e09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = table('roles', column('role_name',String))

    op.bulk_insert(roles_table,[
        {"role_name":"super_admin", "role_id":1},
        {"role_name":"admin", "role_id":2},
        {"role_name":"user", "role_id":3}
    ])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = table('roles',
    column('role_name',String),
    column('role_id',Integer)
    )

    op.execute(
        roles_table.delete().where(
            roles_table.c.role_name.in_(['super_admin','admin','user'])
        )
    )
    
    pass
    # ### end Alembic commands ###
